### ISSUE TITLE
Use the old version of service support v3.6.1

### ISSUE THREAD

**Issue by slzcc** [rabbitmq/rabbitmq-prometheus#14]
Currently don't want to by the upgrade version to solve the plug-in support, what better way?
I have put the plugins copy the contents to the old version but not properly installed.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin only supports `3.8.x` at the moment and a backport to `3.7.x` is under consideration but not guaranteed.

RabbitMQ 3.6.x has been [out of support for almost 18 months now](https://www.rabbitmq.com/versions.html). `3.6.1` specifically is [3.5 years old](https://www.rabbitmq.com/changelog.html). Sorry but you have to upgrade. 3.7 goes out of support in March 2020.

**Comment by slzcc** [comment]
I'll try the other method.
Thank you.

**Comment by michaelklishin** [comment]
[This 3rd party exporter](https://github.com/deadtrickster/prometheus_rabbitmq_exporter#installation) has a version that supports 3.6 but you won't be able to use some of our Grafana dashboards with it.

**Comment by slzcc** [comment]
I currently have tested this method, but it is based on the management api, but our production environment requirements are not open to the management plugin, because it might at some point occur a lot of memory usage issues, currently don't know what the problem caused, the current node memory is 128+that. I am currently unclear how management of Troubleshooting, because it is in my company before it has been closed.

**Comment by michaelklishin** [comment]
There is a [doc guide for that](https://www.rabbitmq.com/memory-use.html). What you are looking it is a single node collecting all the stats, something that was addressed [in `3.6.7`](https://www.rabbitmq.com/changelog.html). `3.6.1` is 15 patches behind even in the out-of-support `3.6.1` version.

**Comment by slzcc** [comment]
Are investigation whether there is a known issue. 
Thanks！

**Comment by michaelklishin** [comment]
A [Blue/Green Deployment upgrade](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/pull/117) to `3.8.1` (when it is out which should be very soon) sounds like the most pragmatic approach.

**Comment by michaelklishin** [comment]
@slzcc I'm not sure I understand your comment but see release notes for `3.6.7`. Statistics DB memory consumption has been effectively a solved problem since then (assuming connections and queues are reasonably evenly distributed between nodes). There's also a [pretty extensive guide on monitoring](https://www.rabbitmq.com/monitoring.html) which compares this plugin to the management one.

**Comment by slzcc** [comment]
The team did not want to use the upgrade version of the method to solve this problem, because there is no so much energy to do this thing, is to use the most simple solution is by writing a service exposed some of the indicators to solve the problem, so that the current service without any perception.
May then over a period of time before upgrading to 3.8. x releases, but also through the many environmental checks before they can upgrade.
Thanks！
