### ISSUE TITLE
Is it possible to disable some metrics from being exposed?

### ISSUE THREAD

**Issue by olgakorichkovskaya** [rabbitmq/rabbitmq-prometheus#25]

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
No, it's not possible. The endpoint will serve everything [from a hardcoded list](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl#L55).

**Comment by michaelklishin** [comment]
It is now possible to aggregate metrics (in fact, the plugin does this by default). [Relevant documentation section](https://www.rabbitmq.com/prometheus.html#metric-aggregation).
