### ISSUE TITLE
Individual queues

### ISSUE THREAD

**Issue by DaiZack** [rabbitmq/rabbitmq-prometheus#44]
I saw the issue #9 
Can we used to have the queue information exposed few months ago.
But now we cannot see the queue information again. (we are now using the rabbimq 3.8.3)
Is the new version turned off the output or do I need to change any settings?

PS: I also tried installing the 3 node Rabbitmq-Prometheus from docker following the official documentation. I cannot see the individual queue information either.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You need to [disable metric aggregation](https://www.rabbitmq.com/prometheus.html#metric-aggregation).

Visualizing per-queue metrics has its limits. No chart will display 50K lines in a way that makes sense so disabling aggregation only makes sense if there are few objects. #24 highlights another side of this issue: if the API endpoint has to return, say, 30 rows per object then responses with 169K objects will be so large that scraping becomes practically impossible.
