### ISSUE TITLE
Get timestamp of queue using rabbitmq_management

### ISSUE THREAD

**Issue by garlickim** [rabbitmq/rabbitmq-prometheus#46]
I want to get timestamp of queue using [rabbitmq-prometheus](https://github.com/rabbitmq/rabbitmq-prometheus) plugin and [rabbitmq_message_timestamp.](https://github.com/rabbitmq/rabbitmq-message-timestamp)

Bcz I want know old message..

If I use rabbitmq_message_timestamp plugin, I could not get the metric(queue timestamp).
But When I use [external exporter](https://github.com/kbudde/rabbitmq_exporter)- kbudde/rabbitmq_exporter- , I can get the metric.

I want to use rabbitmq_message_timestamp plugin and rabbitmq-prometheus plugin together..

plz help me..

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin does not interact with `rabbitmq_message_timestamp` or vice versa. The 3rd party exporter likely exposes the head queue timestamp but this plugin does not.

It does not mean that `rabbitmq_message_timestamp` is not stamping messages, only that its related metric is not exposed.

"Queue timestamp" is not a metric that RabbitMQ tracks. Most likely you are referring to the timestamp of the message at the head of the queue. This metric is a leaked implementation detail and we are not convinced that exposing it in this plugin is a good idea. Consider designing your system without depending on it, e.g. by using message TTL together with dead-lettering (so that expired messages are dead lettered and routed elsewhere).
