### ISSUE TITLE
Unable to disable metrics aggregation through configuration

### ISSUE THREAD

**Issue by lechen26** [rabbitmq/rabbitmq-prometheus#47]
Hi

i have a RabbitMQ deployment on K8s which includes configmap that includes all configuration and enabled plugins. which one of them is rabbitmq_prometheus

the image i'm using is: rabbitmq:3.8.2

i'm trying to set:
` prometheus.return_per_object_metrics = true`

and get the following error:

> 18:47:07.183 [error] You've tried to set prometheus.return_per_object_metrics, but there is no setting with that name.
> 18:47:07.183 [error]   Did you mean one of these?
> 18:47:07.257 [error]     prometheus.ssl.honor_ecc_order
> 18:47:07.257 [error]     prometheus.ssl.reuse_sessions
> 18:47:07.257 [error]     prometheus.tcp.compress

i thougth at first that maybe the plugin wasnt anable first, but i do able to configure other property such as:
`prometheus.tcp.port =  15692`

i do able to enable it at runtime using:
`rabbitmqctl eval 'application:set_env(rabbitmq_prometheus, return_per_object_metrics, true).'`

what am i missing?
thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Object aggregation was [introduced in 3.8.3](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.3) (#28).

**Comment by michaelklishin** [comment]
You can set `rabbitmq_prometheus.return_per_object_metrics` at runtime like any other application key but in `3.8.2` it won't be used.
