### ISSUE TITLE
queue metrics on mirrored queues

### ISSUE THREAD

**Issue by lechen26** [rabbitmq/rabbitmq-prometheus#48]
Hi

i have a cluster of RabbitMQ with 2 nodes with a mirror between them on all queues. (ha-all).
i've used to use the prometheus_rabbitmq_exporter and was able to see metrics from both nodes with pretty much the same values, for example rabbitmq_queue_messages on specific queue from node1 and node2 usually had the same value, or at least close.

i've switched now to use the built it rabbitmq_prometheus (in version 3.8.2), and seems like although the queues are mirrored the same, i only see metrics from the master node.
when executing query on prometheus for queue_messages_ready i only see data from master node.
here is the graph, for queue_messages_ready on specific queue, you can see once i've switched the master node , the data starting to arrives from his exporter.
![image](https://user-images.githubusercontent.com/7347506/84863354-79dabb80-b07d-11ea-8dd0-1a2905082b38.png)

how can i resolved this?
10x

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
