### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by GJaminon** [rabbitmq/rabbitmq-prometheus#52]
Hi,

I don't see anywhere where we can protect the /metric endpoint with some authentication (basic, cert, ...).

It that even possible ? 

Thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin can use HTTPS. It uses the same [setting names](https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/priv/schema/rabbitmq_prometheus.schema#L52) as [TLS for core RabbitMQ listeners](https://www.rabbitmq.com/ssl.html#enabling-tls) but prefixed with `prometheus.ssl.*`, such as

 * `prometheus.ssl.certfile`
 * `prometheus.ssl.keyfile`
 * `prometheus.ssl.cacertfile`

We will add a section to the Prometheus guide as it is extremely beginner-oriented at the moment.
