### ISSUE TITLE
metrics for nodes in a cluster

### ISSUE THREAD

**Issue by haarchri** [rabbitmq/rabbitmq-prometheus#59]
today we had the problem that 2 rabbitmq nodes are available but not in the cluster - but we see both with metrics in prometheus 

is it possible to get the metrics via rabbitmq-prometheus to monitor if a cluster member is not part of a cluster anymore ? we didn't find a metric like this - possible is the amount of members because we didn't use autoscaling 

insights:
situation:
![image](https://user-images.githubusercontent.com/21083497/93593011-8be93480-f9b3-11ea-8289-5f7d97699d4e.png)

expected:
![image](https://user-images.githubusercontent.com/21083497/93592981-7f64dc00-f9b3-11ea-8440-af942b76a228.png)

**Comment by michaelklishin** [comment]
Total number of cluster members 
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
